@startuml
title Pairing Procedure
:Determine if your receiver has an external or internal learn button.\nIf there is no external learn button, remove the lid on the receiver using a #1 phillips screwdriver.\n[[rx_components.jpg Click here for help identifying the learn button.]];
:Cycle power on the receiver by disconnecting the power cord then plugging it back in.;
:Wait 10 seconds then push and hold down the learn button on the receiver.;
:While continuing to hold the learn button down, press any button on the transmitter.;
:The status light on the receiver should flash <color:green>GREEN</color> to indicate that it is paired with the transmitter.\n(Watch closely. The flash can happen quickly and easily be missed) \n If the status light is flashing <color:red>RED</color>, the receiver is indicating that it is getting messages, but not paired with the transmitter.;
:Release the buttons and verify system operation.;
:If removed for access to internal learn button, replace lid on receiver.;
:Done;
@enduml