@startuml
title Testing Power Supply
if (Visually inspect the power supply and cables.  Is there any obvious damage?) then (Yes)
else (No)
    :Unplug the barrel connector of the AC adaptor from the receiver.\nPlug the AC adaptor into a working AC outlet.\nUsing a voltage meter, measure the DC voltage between the center contact and outer contact of the barrel connector.;
    if (Is the voltage read at least 12V?) then (Yes)
        :[[http://rfhero.com/request-rma.php{Click here to go to the Send for repair (RMA) page.}Send receiver for repair (RMA)]];
        stop
    else (No)
    endif
endif
:[[https://www.rfhero.net/accessories Replace AC Adaptor]];
@enduml
add inspect of cable
